export const data = [
  {
    id: 0,
    title: "Little Lemon project",
    liveUrl: " https://ahmedelshenawy0.github.io/Little-Lemon/",
    githubUrl: "https://github.com/AhmedElshenawy0/Little-Lemon",
    image: "/images/lemon.jpg",
    source: "/images/qqq.PNG",
    skills: "HTML5 - Css3 - JavaScript - React .",
    desc: "A simple landing page",
    time: "Sep 20, 2023",
  },
  {
    id: 1,
    title: "Safary app",
    liveUrl: "https://ahmedelshenawy0.github.io/safary-app/",
    githubUrl: "https://github.com/AhmedElshenawy0/safary-app",
    image: "/images/pro.png",
    source: "/images/qqq.PNG",
    skills: "HTML5 - Css3 - JavaScript - React .",
    desc: "Safary app specialized in booking and informing about trips in an attractive way",
    time: "Aug 3, 2023",
  },
  {
    id: 2,
    title: "Book app",
    liveUrl: "https://ahmedelshenawy0.github.io/Book-store/",
    githubUrl: "https://github.com/AhmedElshenawy0/Book-store",
    image: "/images/Capture.jpg",
    source: "/images/qqq.PNG",
    skills: "HTML5 - Css3 - JavaScript - React .",
    desc: "Book app specialized in booking and informing about books",
    time: "May 13, 2023",
  },
  {
    id: 3,
    title: "Landing page",
    liveUrl: " https://ahmedelshenawy0.github.io/Landing-Page/",
    githubUrl: "https://github.com/AhmedElshenawy0/Landing-Page",
    image: "/images/Landing1.jpg",
    source: "/images/landingjj.PNG",
    skills: "HTML5 - Css3 .",
    desc: "A simple landing page",
    time: "Feb 8, 2023",
  },
  {
    id: 4,
    title: "Kasper app project",
    liveUrl: "https://ahmedelshenawy0.github.io/Kasper-template",
    githubUrl: "https://github.com/AhmedElshenawy0/Kasper-template",
    image: "/images/kasper.jpg",
    source: "/images/landingjj.PNG",
    skills: "HTML5 - Css3 .",
    desc: "A simple landing page",
    time: "Nov 22, 2022",
  },
];
