import Head from "next/head";
import "./globals.css";
import { Rubik } from "next/font/google";
import Navbar from "./component/Navbar/Navbar";
import { ModeProvider } from "./context/ModeContext";
import Footer from "./component/Footer/Footer";
import { MousePosition } from "./mouseMotion";
import { MouseProvider } from "./mouseMotion";
const inter = Rubik({
  weight: ["400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Ahmed ELshenawy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MouseProvider>
          <ModeProvider>
            <Navbar />
            {children}
            <Footer />
          </ModeProvider>
        </MouseProvider>
      </body>
    </html>
  );
}
